require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MyTestApp' do

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary/Permission-MediaLibrary.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone/Permission-Microphone.podspec"
  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'
  pod 'RNCustomizedImagePicker', :path => '../node_modules/react-native-customized-image-picker/RNCustomizedImagePicker.podspec'
  pod 'RNSoundRecorder', :path => '../node_modules/react-native-sound-recorder'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  # pod 'React', :path => '../node_modules/react-native', :subspecs => [    
  #   'RCTPushNotification',
  # ]
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  #  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
  # pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'
  pod 'RNVoipPushNotification', :path => '../node_modules/react-native-voip-push-notification'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec'
  pod 'OneSignal', '>= 3.0', '< 4.0'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-in-app-review', :path => '../node_modules/react-native-in-app-review'
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  target 'MyTestAppTests' do
    inherit! :complete
    # Pods for testing
  end
  # use_frameworks!
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

end